version: '3'

services:
  evalSpringMysqlSec:
    image: mysql:5.6
    container_name: springbootk8sdemo
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=evalspringsecdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - 3306:3306

  springbootk8sdemo:
    image: springbootk8sdemo:latest
    container_name: springbootk8sdemo
    ports:
      - 8088:8088
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://evalSpringMysqlSec:3306/evalspringsecdb?autoReconnect=true&useSSL=false
    depends_on:
      - evalSpringMysqlSec
