apiVersion: v1
kind: Service
metadata:
  name: springbootk8sdemo-service
spec:
  selector:
    app: springbootk8sdemo

  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

  type: NodePort